import React, { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { 
  Users, 
  User,
  Calendar, 
  Video, 
  Zap, 
  ArrowUpRight, 
  MoreHorizontal, 
  Clock, 
  CheckCircle2,
  AlertCircle,
  Activity
} from 'lucide-react';
import { cn } from '../lib/utils';
import { Link } from 'react-router-dom';
import { collection, query, where, onSnapshot, orderBy, limit, getDoc, doc } from 'firebase/firestore';
import { auth, db } from '../firebase';

export const DoctorDashboard: React.FC = () => {
  const [userName, setUserName] = useState('Doctor');
  const [appointments, setAppointments] = useState<any[]>([]);
  const [stats, setStats] = useState([
    { label: 'Total Patients', value: '0', change: '+0%', icon: Users, color: 'bg-brand-50 text-brand-600' },
    { label: 'Appointments', value: '0', change: '+0%', icon: Calendar, color: 'bg-emerald-50 text-emerald-600' },
    { label: 'Consultations', value: '0', change: '+0%', icon: Video, color: 'bg-blue-50 text-blue-600' },
    { label: 'AI Insights', value: '0', change: '+0%', icon: Zap, color: 'bg-purple-50 text-purple-600' },
  ]);

  useEffect(() => {
    if (!auth.currentUser) return;

    // Fetch User Name
    const fetchUser = async () => {
      const userDoc = await getDoc(doc(db, 'users', auth.currentUser!.uid));
      if (userDoc.exists()) {
        const data = userDoc.data();
        setUserName(`${data.firstName} ${data.lastName}`);
      }
    };
    fetchUser();

    // Fetch Appointments for today
    const today = '2026-03-23'; // Using current date from context
    const q = query(
      collection(db, 'appointments'),
      where('doctorId', '==', auth.currentUser.uid),
      where('date', '==', today),
      orderBy('time', 'asc')
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const apts = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setAppointments(apts);
      
      // Update stats
      setStats(prev => prev.map(stat => {
        if (stat.label === 'Appointments') {
          return { ...stat, value: snapshot.size.toString() };
        }
        return stat;
      }));
    });

    // Fetch Total Patients (unique patientIds in appointments)
    const patientsQuery = query(
      collection(db, 'appointments'),
      where('doctorId', '==', auth.currentUser.uid)
    );
    const unsubscribePatients = onSnapshot(patientsQuery, (snapshot) => {
      const uniquePatients = new Set(snapshot.docs.map(doc => doc.data().patientId));
      setStats(prev => prev.map(stat => {
        if (stat.label === 'Total Patients') {
          return { ...stat, value: uniquePatients.size.toString() };
        }
        return stat;
      }));
    });

    // Fetch Consultations
    const consultationsQuery = query(
      collection(db, 'consultations'),
      where('doctorId', '==', auth.currentUser.uid)
    );
    const unsubscribeConsultations = onSnapshot(consultationsQuery, (snapshot) => {
      setStats(prev => prev.map(stat => {
        if (stat.label === 'Consultations') {
          return { ...stat, value: snapshot.size.toString() };
        }
        return stat;
      }));
    });

    return () => {
      unsubscribe();
      unsubscribePatients();
      unsubscribeConsultations();
    };
  }, []);

  const [aiInsights, setAiInsights] = useState<any[]>([]);

  useEffect(() => {
    if (!auth.currentUser) return;
    // In a real app, these would be generated by a cloud function or AI service
    // For now, we'll fetch from a 'insights' collection if it exists, or show empty
    const q = query(
      collection(db, 'insights'),
      where('doctorId', '==', auth.currentUser.uid),
      limit(3)
    );
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const insights = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setAiInsights(insights);
    });
    return () => unsubscribe();
  }, []);

  return (
    <div className="space-y-10">
      {/* Welcome Header */}
      <div className="flex justify-between items-end">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-4xl font-display font-extrabold text-slate-900 mb-2">Good Morning, Dr. {userName}</h1>
          <p className="text-slate-500 text-lg">You have {appointments.length} appointments scheduled for today.</p>
        </motion.div>
        <div className="flex gap-3">
          <button className="px-6 py-3 bg-white border border-slate-100 rounded-2xl font-bold text-sm text-slate-600 hover:bg-slate-50 transition-all">
            Download Report
          </button>
          <Link to="/doctor/appointments" className="px-6 py-3 bg-brand-600 text-white rounded-2xl font-bold text-sm shadow-lg shadow-brand-500/20 hover:bg-brand-700 transition-all">
            + New Appointment
          </Link>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <Link
            key={stat.label}
            to={stat.label === 'Appointments' ? '/doctor/appointments' : stat.label === 'Consultations' ? '/doctor/consultations' : '#'}
            className="bg-white p-6 rounded-4xl border border-slate-100 shadow-sm hover:shadow-md transition-all group block"
          >
            <div className="flex justify-between items-start mb-4">
              <div className={cn("w-12 h-12 rounded-2xl flex items-center justify-center transition-transform group-hover:scale-110", stat.color)}>
                <stat.icon className="w-6 h-6" />
              </div>
              <div className={cn(
                "flex items-center gap-1 text-xs font-bold px-2 py-1 rounded-full",
                stat.change.startsWith('+') ? "bg-emerald-50 text-emerald-600" : "bg-rose-50 text-rose-600"
              )}>
                {stat.change}
                <ArrowUpRight className="w-3 h-3" />
              </div>
            </div>
            <p className="text-slate-500 text-sm font-medium mb-1">{stat.label}</p>
            <h3 className="text-3xl font-display font-bold text-slate-900">{stat.value}</h3>
          </Link>
        ))}
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        {/* Appointment Queue */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="lg:col-span-2 bg-white rounded-4xl border border-slate-100 shadow-sm overflow-hidden"
        >
          <div className="p-8 border-b border-slate-50 flex justify-between items-center">
            <h2 className="text-xl font-display font-bold text-slate-900">Appointment Queue</h2>
            <Link to="/doctor/appointments" className="text-brand-600 font-bold text-sm hover:underline">View All</Link>
          </div>
          <div className="divide-y divide-slate-50">
            {appointments.length > 0 ? appointments.map((apt) => (
              <div key={apt.id} className="p-6 flex items-center gap-6 hover:bg-slate-50/50 transition-colors group">
                <div className="w-14 h-14 rounded-2xl bg-slate-100 overflow-hidden shrink-0 flex items-center justify-center">
                  <User className="w-6 h-6 text-slate-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <h4 className="font-bold text-slate-900 truncate">{apt.patientName}</h4>
                  <p className="text-sm text-slate-500">{apt.type}</p>
                </div>
                <div className="flex items-center gap-2 text-slate-500 font-medium text-sm">
                  <Clock className="w-4 h-4" />
                  {apt.time}
                </div>
                <div className="w-32">
                  <span className={cn(
                    "px-4 py-1.5 rounded-full text-xs font-bold inline-block w-full text-center",
                    apt.status === 'In Progress' ? "bg-brand-50 text-brand-600" :
                    apt.status === 'Waiting' ? "bg-amber-50 text-amber-600" :
                    "bg-slate-50 text-slate-500"
                  )}>
                    {apt.status}
                  </span>
                </div>
                <button className="p-2 text-slate-400 hover:text-slate-900 transition-colors">
                  <MoreHorizontal className="w-5 h-5" />
                </button>
              </div>
            )) : (
              <div className="p-20 text-center text-slate-400">
                <Calendar className="w-12 h-12 mx-auto mb-4 opacity-20" />
                <p>No appointments scheduled for today.</p>
              </div>
            )}
          </div>
        </motion.div>

        {/* AI Insights Sidebar */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, delay: 0.5 }}
          className="space-y-6"
        >
          <div className="bg-brand-600 rounded-4xl p-8 text-white relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <Zap className="w-24 h-24" />
            </div>
            <div className="relative z-10">
              <div className="w-12 h-12 bg-white/20 backdrop-blur-xl rounded-2xl flex items-center justify-center mb-6">
                <Zap className="w-6 h-6" />
              </div>
              <h3 className="text-2xl font-display font-bold mb-2">AI Clinical Assistant</h3>
              <p className="text-brand-100 mb-6 leading-relaxed">I've analyzed patient records today. Here are the critical findings.</p>
              <button className="w-full py-3 bg-white text-brand-600 rounded-2xl font-bold text-sm hover:bg-brand-50 transition-all">
                Review All Insights
              </button>
            </div>
          </div>

          <div className="bg-white rounded-4xl border border-slate-100 shadow-sm p-8">
            <h3 className="text-lg font-display font-bold text-slate-900 mb-6 flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-rose-500" />
              Critical Alerts
            </h3>
            <div className="space-y-6">
              {aiInsights.map((insight) => (
                <div key={insight.id} className="group cursor-pointer">
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="font-bold text-slate-900 group-hover:text-brand-600 transition-colors">{insight.title}</h4>
                    <span className={cn(
                      "px-2 py-0.5 rounded-md text-[10px] font-black uppercase tracking-wider",
                      insight.severity === 'High' ? "bg-rose-50 text-rose-600" : "bg-amber-50 text-amber-600"
                    )}>
                      {insight.severity}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 mb-2">Patient: <span className="font-bold text-slate-700">{insight.patient}</span></p>
                  <p className="text-sm text-slate-600 leading-relaxed">{insight.desc}</p>
                  <div className="mt-4 h-px bg-slate-50 group-last:hidden" />
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>

      {/* Health Trends Chart Placeholder */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.6 }}
        className="bg-white rounded-4xl border border-slate-100 shadow-sm p-10"
      >
        <div className="flex justify-between items-center mb-10">
          <div>
            <h2 className="text-2xl font-display font-bold text-slate-900">Practice Performance</h2>
            <p className="text-slate-500">Patient volume and consultation trends over the last 30 days.</p>
          </div>
          <div className="flex gap-2">
            <button className="px-4 py-2 bg-slate-50 text-slate-600 rounded-xl text-xs font-bold hover:bg-slate-100 transition-all">Week</button>
            <button className="px-4 py-2 bg-brand-600 text-white rounded-xl text-xs font-bold shadow-lg shadow-brand-500/20 transition-all">Month</button>
          </div>
        </div>
        <div className="h-80 w-full bg-slate-50 rounded-3xl flex items-center justify-center border-2 border-dashed border-slate-200">
          <div className="text-center">
            <Activity className="w-12 h-12 text-slate-300 mx-auto mb-4" />
            <p className="text-slate-400 font-medium">Interactive Analytics Chart Will Render Here</p>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default DoctorDashboard;
